# Generated by Django 5.0.4 on 2024-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Gender", models.FloatField(max_length=20)),
                ("Age", models.FloatField(max_length=20)),
                ("Smoking", models.FloatField(max_length=20)),
                ("Fatigue", models.FloatField(max_length=20)),
                ("Allergy", models.FloatField(max_length=20)),
            ],
        ),
    ]
